# Generated by Django 2.2.16 on 2022-09-11 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220911_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='following_user',
            new_name='following',
        ),
    ]
